function [fitresult, gof] = poly4(I_int, non2_down)
%CREATEFIT(I_INT,NON2_DOWN)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : I_int
%      Y Output: non2_down
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Nov-2019 18:53:19


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( I_int, non2_down );

% Set up fittype and options.
ft = fittype( 'poly4' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'non2_down vs. I_int', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel I_int
% % ylabel non2_down
% % grid on


