function [fitresult, gof] = expFitdouble(et, e200n)
%CREATEFIT(ET,E200N)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : et
%      Y Output: e200n
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Nov-2019 13:03:56


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( et, e200n );

% Set up fittype and options.
ft = fittype( 'a*(1-b*exp(-c*x)-d*exp(-e*x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [0.12909489216605 0.786338088027946 0.475967786980815 0.0888930235728137 0.520498254930125];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'e200n vs. et', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel et
% ylabel e200n
% grid on


